### ISSUE TITLE
Unable to import Colorbar 

### ISSUE THREAD

**Issue by pskeshu** [ppinard/matplotlib-colorbar#11]
```
Traceback (most recent call last):
  File "plot_this.py", line 6, in <module>
    from matplotlib_colorbar.colorbar import Colorbar
  File "/usr/lib/python3.7/site-packages/matplotlib_colorbar/colorbar.py", line 41, in <module>
    from matplotlib.cbook import is_string_like
ImportError: cannot import name 'is_string_like' from 'matplotlib.cbook' (/usr/lib/python3.7/site-packages/matplotlib/cbook/__init__.py)
```
System info:
```
Python 3.7.0 (default, Sep 15 2018, 19:13:07) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib as mlab
>>> mlab.__version__
'3.0.0'
>>> import matplotlib_colorbar as mcb
>>> mcb.__version__
'0.3.5'
>>> from matplotlib_colorbar.colorbar import Colorbar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/matplotlib_colorbar/colorbar.py", line 41, in <module>
    from matplotlib.cbook import is_string_like
ImportError: cannot import name 'is_string_like' from 'matplotlib.cbook' (/usr/lib/python3.7/site-packages/matplotlib/cbook/__init__.py)
>>> 
```

**Comment by ppinard** [comment]
Thank you for reporting this error. It was supposed to be fixed in 0.3.6 but that version was never uploaded to PyPI :disappointed: In any case your issue made me fixed a few other things that did not work with matplotlib 3.0. 

Could you please update `matplotlib-colorbar` (the new version should be 0.3.7) and try again?

**Comment by pskeshu** [comment]
Thank you for the fix!
Although the old problem is gone, I'm getting a different error now. :disappointed: 

```
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/figure.py", line 2097, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/figure.py", line 1652, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2604, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.7/site-packages/matplotlib_colorbar/colorbar.py", line 329, in draw
    ticks, ticklabels, offset_string = calculator.calculate_ticks()
  File "/usr/lib/python3.7/site-packages/matplotlib_colorbar/colorbar.py", line 174, in calculate_ticks
    return self._base._ticker()
TypeError: _ticker() missing 2 required positional arguments: 'locator' and 'formatter'
```

**Comment by pskeshu** [comment]
![test](https://user-images.githubusercontent.com/7001840/48489050-2290bb80-e848-11e8-8fd3-1fa921f77286.png)
The colorbar looks small, and set_ticks seems to have no effect. :(

**Comment by pskeshu** [comment]
Hi, just wanted to find out if there's a possible way to fix this. I would be happy to fix the problem if you point me at the right direction.

**Comment by ppinard** [comment]
Could you try again with the new version (0.4.0)? I think matplotlib 3.x changed the way the color bar is calculated and broke matplotlib-colorbar.
